### ISSUE TITLE
Créer un script et de la doc pour générer la documentation en local.

### ISSUE THREAD

**Issue by NelleV** [AFPy/python_doc_fr#2]
Créer un script et de la doc pour générer la documentation en local.

**Comment by JulienPalard** [comment]
Hop, script à tout faire, fetch upstream, merge pot, génération en local:

https://github.com/JulienPalard/python_doc_fr/blob/master/sync.sh

**Comment by JulienPalard** [comment]
`sync.sh` est maintenant sur la l'upstream/master, tout le monde peut l'utiliser.
