### ISSUE TITLE
la liste des .po ne se met pas à jour automatiquement

### ISSUE THREAD

**Issue by grenoya** [AFPy/python_doc_fr#27]
Lors de changements dans les noms de fichiers upstream, les nouveaux fichiers .po ne sont pas générés et intégrés au dépôt github automatiquement.

Il faut : 
* vérifier la liste actuelle
* relancer le script
* vérifier si certaines parties du texte n'a pas été déplacé dans un autre fichier
* dans ce cas, il faudra recopier les traductions déjà effectuées

**Comment by JulienPalard** [comment]
Pour des raisons de "bah ça marche plus", je me suis refait un script, que je me suis push dans mon repo, https://github.com/JulienPalard/python_doc_fr/blob/master/sync.sh et je me le passe de temps en temps.

Si ça peut aider...

**Comment by JulienPalard** [comment]
Bon en ce moment c'est toujours pas automatique, le script est trop jeune pour que je le laisse tourner seul, mais je le fais tourner régulièrement, donc c'est plus vraiment un problème, et quand j'aurais pu constater qu'il est correct, ou fixer les derniers soucis, j'le collerai dans une crontab.

**Comment by JulienPalard** [comment]
Maintenant que n'importe qui peut le mettre à jour via un `./scripts/sync.sh`, est-ce qu'on veut réelement l'automatiser dans un cron ?

**Comment by JulienPalard** [comment]
Je ferme ce ticket, une action humaine sur ce sujet n'est pas un mauvais point: L'humain peut review, et aussi, si personne ne commit pendant un mois, on se passe de 30 commits innutils du cron.
