### ISSUE TITLE
Licences à traduire ou pas ?

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/python_doc_fr#30]
Je me demande si on doit traduire les licences ici:

http://www.afpy.org/doc/python/3.5/license.html

A mon avis non, à mon avis elles ne devrait même pas figurer dans les `.po`, (comme du code) d'ailleurs certaines licences sont dans ce genre de blocs (typiquement celui de Mersene Twiter).

Mais c'est un avis de dev, pas d'avocat :-p

En attendant, vu que c'est pas le plus urgent, j'y touche pas.

**Comment by grenoya** [comment]
Si je ne me trompe pas, les licences ne sont valables que dans la langue dans laquelle elles sont écrites au départ. Je veux dire par là que lorsque l'on utilise un LL, on doit garder le fichier de licence intouché (ie ne pas le traduire), sauf si la licence est permissive au point d'avoir le droit d'en changer.

Je suis donc d'avis de ne pas traduire et, éventuellement, de pointer vers les traductions officielles des licences pour lesquelles cette trad officielle existe.

**Comment by JulienPalard** [comment]
J'ouvrirai bien un bug pour leur proposer de les virer des .po (en les mettant dans des blocs (dont j'ignore le nom) comme le code (et comme les licences suivantes).

**Comment by JulienPalard** [comment]
Ticket clos, on ne traduit pas, cf: http://bugs.python.org/issue26106
