### ISSUE TITLE
Trad' faq.po

### ISSUE THREAD

**Issue by amaddah** [AFPy/python_doc_fr#31]
Yop,

C'est pour prévenir que je vais essayer de traduire faq.po.

J'essayerai de mettre mon avancée ici afin d'à la fois me motiver mais aussi d'avoir un endroit où recenser d'éventuels soucis.

**Comment by JulienPalard** [comment]
N'oublie pas de lire le README en entier, il contient pas mal d'informations, liens, conseils, et traudctions qui t'aideront :-)

**Comment by amaddah** [comment]
C'est fait, merci !

J'ai eu un petit souci tout à l'heure avec le mot "awaitable"

Je l'ai traduit par "temporisable", mais j'ai pas l'impression que ce soit vraiment le bon mot, qu'en pensez vous ?

**Comment by JulienPalard** [comment]
Toute cette série de vocabulaire est complexe à traduire.

Comme le dit le `README`, le glossaire est entièrement traduit et donc une bonne piste à explorer quand tu te pose une question, et il se trouve que awaitable y est: http://afpy.org/doc/python/3.5/glossary.html#term-awaitable

Et comme tu le voit, il n'est pas traduit, voilà mon chemin de reflexion, discutable:

Certains mots sont, en Python et donc dans sa doc, en plus d'être des mots anglais, des noms de classes, et donc des nom propres.

Par exemple *byte*, c'est un mot, mais aussi le nom d'un type, que j'aurais tendence à traduire dans "A byte is, nowadays, 8 bits long" (Un octet, de nos jours, fait huit bits) mais  pas dans ":meth:`encode` returns a byte object" (:meth:`encode` donne un objet *byte*).

Revenons au cas de *awaitable* en passant par le cas de *await*:

Je n'ai pas envie de traduire *await* car c'est pour moi dans la plupart des cas (pas tous, c'est aussi un mot) le mot-clef utilisé par la syntaxe python pour déclarer une coroutine, et vu qu'on ne traduit pas la syntaxe de Python mais la doc. C'est un peu raccourci comme reflexion, mais j'ai quand même envie que dans le cerveau des gens, lorsqu'ils lisent "Une expression await peut le faire", *await* de la doc soit le *await* du code, qu'il y ai un lien un pour un. En d'autres mots il ne faut pas que la traduction devienne un obstacle à la compréhension.

Si on ne traduit pas *await*, je pense qu'on ne doit pas non plus traduire *awaitable*, encore une fois, pour qu'il lien explicit se fasse dans l'esprit du lecteur entre *await* et *awaitable*.

Pour terminer, je pense que *awaitable* est tout à fait compréhensible par un français ne parlant pas anglais, bien que ce ne soit **pas** du français.

Puisque ce n'est pas du français valide, je propose de mettre ces mots en italique (entourés d'étoiles: \*awaitable\*, ce qui donne *awaitable*) pour manifester, avouer, explicitement que ce n'est pas français, que c'est faux, qu'on le sait, et qu'on assume, parce qu'on pense que c'est bon pour la lisibilité et le lecteur, et que c'est pas la peine de nous ouvrir un ticket sur le sujet aussi en passant.


D'un autre côté, il existe des traductions pour *await* et *awaitable*, et *temporisable* n'est pas déconnant du tout, c'est plutôt même bien trouvé. Peut être qu'un jour on sera suffisament nombreux sur la traduction pour échanger des arguments, voir voter sur ces sujets ^-^

**Comment by amaddah** [comment]
Merci beaucoup pour votre réponse bien détaillée !

Ouais, je suis tout à fait d'accord avec vous. En tant que développeur, personnellement, j'ai tendance à préférer voir les noms des classes/méthodes directement au lieu d'avoir une traduction qui va plus m'embêter qu'autre chose. D'un point de vue pratique, je me dis exactement la même chose et je pense que c'est la bonne manière de voir les choses.

Ok pour les mettre en *italique*, je vais essayer d'adopter cette pratique, je l'avais lu tout à l'heure sur le README mais complétement oublié lorsque je me suis lancé à traduire quelques phrases.

Après, d'un point de vue normalisation, ça sera toujours discutable de toute façon. En tout cas, pour le cas présent, c'est beaucoup plus clair pour moi, Merci!

**Comment by JulienPalard** [comment]
De rien ! Je clos donc le ticket (et pour répondre à ta question sur crowdin, tu peux me tutoyer ;-))

**Comment by JulienPalard** [comment]
(Tiens je n'avais pas vu que tu avais ré-utilisé le ticket de réservation de faq.po, je réouvre donc)

Et j'en proffite pour préciser que la doc utiliser le format ReStructuredText, ainsi, lorsque tu voit 

    The :class:`float` class

tu ne peux pas traduire par

    La `:class: des « flottants »`

mais :

    La class :class:`float`

Idem, avec les backticks, tu ne peux pas les remplacer par des apostrophes:

    ``x``

se traduit :

    ``x``

au pixel près.

**Comment by amaddah** [comment]
Oui, je me suis dit que c'est mieux de regrouper tout ce qui concerne la discussion sur faq.po ici.

Je pensais que pour certains types (comme int, float, string), une traduction était possible, mais peut être justement pas dans un cas comme ça. Ça marche, tout ce qui est entre `` doit être gardé tel quel.

Merci !

**Comment by grenoya** [comment]
Bonjour, je me permets juste de revenir sur l'exemple de Julien :

"""Par exemple byte, c'est un mot, mais aussi le nom d'un type, que j'aurais tendence à traduire dans "A byte is, nowadays, 8 bits long" (Un octet, de nos jours, fait huit bits) mais pas dans ":meth:encode returns a byte object" (:meth:encode donne un objet byte)."""

Pour le coup 'byte' se traduit en français par 'byte'. 'octet' est un cas particulier (byte de 8 bits), qui n'a pas de traduction en anglais à proprement parlé, donc :+1: 
"A byte is, nowadays, 8 bits long" => "Un byte, de nos jours, fait 8 bits (d'où son nom d'octet en français)"

une fois ça dit, on doit pouvoir traduire par octet dans la suite du document.

**Comment by JulienPalard** [comment]
Byte et octet était effectivement un double exemple vu que octet est une "spécialisation" de *byte*. Mais mon point est surtout que lorsqu'un mot est une classe Python, il est bon pour la compréhension de ne pas le traduire.

Par exemple, *tuple* se traduirait *uplet*, mais vu que *tuple* est aussi un type Python, autant traduire *tuple* par *tuple*. D'ailleurs vu que, une fois traduit, *tuple* est du Python plus que de l'anglais, on pourrait le mettre entre double backticks.

On pourrait préférer dire explicitement que *tuple* c'est du Python :

    Cette fonction donne un ``tuple`` lorsqu'on lui donne les bons arguments.

à indiquer en italique que le mot n'est pas français :

    Cette fonction donne un *tuple* lorsqu'on lui donne les bons arguments.

à mélanger du francais et de l'anglais :

    Cette fonction donne un tuple lorsqu'on lui donne les bons arguments.

à utiliser un mot francais, méconnu, dont le lien avec Python n'est pas direct :

    Cette fonction donne un uplet lorsqu'on lui donne les bons arguments.

**Comment by amaddah** [comment]
Bonjour à vous deux !

Merci beaucoup de prendre le temps de bien détailler et m'éclairer !

Ouais je vois. En fait, j'y ai pas du tout pensé. Mais comme Byte c'est une classe, rien n'empêchait que pour des raisons de performances ou autre (comme en C), une classe Byte prenne 10 ou 20 bits et qu'elle conserve son nom Byte. Je pensais vraiment à l'octet en lui-même. Merci Grenoya.

Du coup Julien :
* C'est bien la traduction 2 qui est la plus approprié ? 
* La 1 est tout à fait possible, non ?
* Pour la 4, c'est du coup pas possible du tout pour des raisons de compréhension et d’ambiguïté.
* Et la 3, comme c'est un mot non français, il faudrait le mettre en avant.

J'y pense, pour des noms classes, il n'est pas aussi préférable de mettre la première lettre en majuscule même si la documentation anglaise n'en utilise pas ?
```
Cette fonction donne un *Tuple* lorsqu'on lui donne les bons arguments.
```

**Comment by JulienPalard** [comment]
Je préfère la première traduction. Ce qui est entre double backticks est toujours quelque chose qu'on peut copier-coller dans un REPL et qui va fonctionner, donc pas de majuscule, juste le nom du type, tel qu'il existe dans Python. Comme ça l'utilisateur sait sans ambiguité qu'on parle d'un ``tuple`` Python, **du tuple** Python.

**Comment by JulienPalard** [comment]
Je suis en train de merger tes phrases et je tombe sur des traductions un peu étranges:

> Les listes, d'autre part, ressemblent davantage à des tableaux dans d'autres langues. Ils ont tendance à contenir un nombre variable d'objets qui ont le même type et qui ne roulent pas sur un par un. Par exemple, ``os.listdir('.')`` retourne une liste de chaînes qui représentent les fichiers dans le répertoire courant. Les fonctions qui opèrent sur cette sortie romprait généralement pas si vous avez ajouté un ou deux autres fichiers dans le répertoire.

Je souligne:

> ... et qui ne roulent pas sur un par un.

WTF ?

Ou encore:

> Les fonctions qui opèrent sur cette sortie romprait généralement pas

Je veux bien que tu utilise des chaînes de markov pour t'aider à traduire, Google Translate, ou même Bing Translate si ça peut te faire gagner du temps (moi Google translate me fait gagner du temps, en me proposant du vocabulaire, basiquement), mais je veux bien que tu relise quand même un petit peu avant de pousser ces traductions :-)

**Comment by JulienPalard** [comment]
J'ai mergé tes traductions, corrigé, pushé sur github, et rsync sur la proprod: http://www.afpy.org/doc/python/3.5/faq/design.html

**Comment by amaddah** [comment]
Salut Julien !

Ouais tu as raison, y a pour certaines traductions où j'ai vraiment pas su prendre ni le temps ni le recul suffisant pour pas écrire une traduction hasardeuse :'(

Je vais essayer de faire plus gaffe pour certaines traductions sensibles.

En fait, je me base généralement sur la traduction Microsoft proposée en ajustant les points que j'estime mal traduits. Mais des fois, il vaut mieux restructurer les phrases complètement. Et dans ces moments, que mon meilleur ami _flemme_ me pousse à pas prendre mon temps. J'utilise aussi google traduction et linguee (pour le contexte). M'enfin dans tous les cas, merci pour la remarque, ça va me pousser à faire plus gaffe.

Merci pour les corrections et la cuisine git !

**Comment by JulienPalard** [comment]
Bonsoir,

J'ai essayé de merger ton travail ce soir, mais je suis tombé sur des traductions approximatives comme:

> Some cleverness is applied to improve the performance of appending items repeatedly

traduit :

> Une certaine ingéniosité est appliquée afin d'améliorer les performances de l'ajout de différents *items* à plusieurs reprises

Je doute que "appliquer une ingéniosité" soit très propre comme tournure, je pense que tu peux traduire *items*, et je pense que sémantiquement il y a une différence entre "repetedly" et "à plusieurs reprise" (dans *repeatedly*, j'entend qu'on va insérer moulte éléments, dans "à plusieurs reprises" j'entend deux ou trois).

Je te laisse relire et corriger tes traductions, je retenterai un merge un peu plus tard.

**Comment by amaddah** [comment]
Salut Julien,

Ok, je vais essayer de relire et corriger mes traductions d'ici mardi prochain.

hum, plutôt :
```
Une façon de faire ingénieuse permet l'amélioration des performances de lors de l'ajout d'un élément à maintes reprises.
``` ?

Je vais m'y repencher dès que je peux.

Bonne fin de soirée

**Comment by JulienPalard** [comment]
Bien meilleur déjà, tu peux peut être jouer avec le mot "fréquemment" qui je pense conserve mieux le sens de "repeatedly".

Peut être aussi parler d'ajout *d'éléments* plutot que d'ajout d'*un élément*", car c'est *items* dans le ``msgid``.

**Comment by amaddah** [comment]
Yooop,

J'ai opté au final pour : 
```
Un savoir-faire ingénieux permet l'amélioration des performances lors de l'ajout fréquent d'éléments
```
J'ai une (plusieurs en faite) : 
* Je voudrais pouvoir avoir un aperçu de mes dernières traductions (genre dans les 5 jours précédents), comment je fais ?
* C'est possible de consulter un message reçu en mode source ? Genre moi pourr afficher les traductions et les mettre en exergue, j'encercle le texte entre ```. C'est un peu tricher non ? Tu utilises quoi toi ?
* Une dernière question, mais c'est de la pure curiosité, c'est juste de savoir un peu comment tu gères les merge des traductions, tu les passes un par un à la main ? ou t'as un outil qui te donne une bonne vision ? genre plusieurs screens et tu peux éventuellement modifier un qui te plait pas trop ?

**Comment by JulienPalard** [comment]
> Je voudrais pouvoir avoir un aperçu de mes dernières traductions (genre dans les 5 jours précédents), comment je fais ? (y a un outil ? moi je vais dans activité et je regarde à la main, pas efficace :()

Côté crowdin je pense qu'il n'y a pas grand chose de plus que activité, cependant avec git, un ``git log --author`` te donnerait à peu près ce que tu veux.

> C'est possible de consulter un message reçu en mode source ? Genre moi pourr afficher les traductions et les mettre en exergue, j'encercle le texte entre ```. C'est un peu tricher non ? Tu utilises quoi toi ?

Je ne comprend absolument pas la question :-( Je pense que je manque de contexte, tu parles de crowdin en particulier ? ou de ReStructuredText ?

> Une dernière question, mais c'est de la pure curiosité, c'est juste de savoir un peu comment tu gères les merge des traductions, tu les passes un par un à la main ? ou t'as un outil qui te donne une bonne vision ? genre plusieurs screens et tu peux éventuellement modifier un qui te plait pas trop ?

D'abord, du moins pour tes traductions, j'utilise le client crowdin, ``crowdin-cli download``, ça me télécharge ce qu'a crowdin, ensuite j'utilise ``git diff`` pour relire en diagonale, soit je m'arrête là (comme hier), soit ça me plait et j'utilise alors ``git add -p`` qui me permet d'ajouter les traductions à un commit une par une, quand je voit une typo / un petit truc à corriger, je le fait à côté avec poedit, finalement je commit et je push.

Pour les traductions des autres, ils utilisent ``poedit``, ils ont *fork* ce dépot git, après avoir tradit, ils me font donc un *pull request*, que je relis (ou grenoya), si on est pas d'accord, on peut laisser un message lié au pull request, l'auteur peut donc le corriger, et quand tout est propre, on a un bouton sur github pour accepter la pull request. Après si la pull request n'est pas mergable automatiquement par github, c'est pas bien compliqué soit de demander à l'auteur de rebase, soit de faire le merge soit même (git remote add, git fetch, git merge, résoudre les conflits, git commit, git push quoi)

**Comment by amaddah** [comment]
Re,

Merci pour ta réponse !

> Je ne comprend absolument pas la question :-( Je pense que je manque de contexte, tu parles de crowdin en particulier ? ou de ReStructuredText ?

Je parle d'ici en faite. Genre quand tu utilises des quotes. C'est bon en fait (c'est le chevron >), j'avais pas bien regardé le tuto Markdown :'(  Mais en gros, si genre quelqu'un utilise un truc que je connais pas, je pourrais regarder directement le code qu'il a écrit et pouvoir le refaire :D 

À l'heure où j'écris, je m'essaye d'installer poedit à la main (enfin lancer un ./configure propre), vive les problèmes de dépendances :(

Et c'est là où je m'aperçois que pour debian, poedit est disponible dans les depôts .. j'ai adoré polluer mon disque dur et ma distribution pour rien, trop fort :D

En tout cas, merci bcp pour les outils (poedit et crowndin-cli) ! 

J'ai bien compris comment tu fais pr les merges, merci pour les détails !

**Comment by JulienPalard** [comment]
Je ferme ce ticket car je centralise les réservations dans https://github.com/AFPy/python_doc_fr/issues/32
