### ISSUE TITLE
Priorités et qui fait quoi

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/python_doc_fr#32]
J'ai obtenu les stats d'accès à `docs.python.org`, on peut en déduire un ordre de priorité que voici, choisissez vos section en partant par le haut de cette liste, et réservez les en commentant ce ticket (pour pas que deux personnes ne travaillent sur le même sujet) :

(Ce qui est terminé est coché, ce qui est réservé indiqué explicitement en gras)

- [x] library/functions.po
- [x] tutorial/datastructures.po
- [ ] library/stdtypes.po **Réservé par @julienpalard**
- [x] tutorial/inputoutput.po
- [x] library/string.po
- [x] library/re.po **Réservé par @grenoya**
- [ ] library/datetime.po **Réservé par @Nodraak**
- [x] tutorial/errors.po
- [ ] library/builtins.po
- [x] tutorial/controlflow.po
- [x] tutorial/classes.po
- [ ] library/builtins.po
- [x] tutorial/modules.po
- [x] library/os.po
- [ ] library/subprocess.po
- [x] library/math.po
- [ ] library/csv.po **Réservé par @Shloub**
- [ ] library/json.po
- [ ] library/functions.po
- [ ] library/random.po
- [ ] library/exceptions.po
- [ ] library/os.path.po
- [ ] library/time.po
- [ ] library/stdtypes.po
- [x] tutorial/introduction.po
- [ ] library/constants.po
- [ ] library/collections.po
- [ ] library/itertools.po
- [x] tutorial/index.po
- [ ] library/unittest.po
- [ ] library/socket.po
- [ ] library/multiprocessing.po
- [ ] library/struct.po
- [ ] library/xml.etree.elementtree.po
- [ ] library/logging.po
- [ ] library/datetime.po
- [ ] library/argparse.po
- [ ] library/threading.po
- [ ] howto/regex.po **Réservé par @crunchylian**
- [x] tutorial/datastructures.po
- [x] tutorial/appetite.po
- [ ] library/index.po
- [x] tutorial/controlflow.po
- [ ] library/argparse.po
- [ ] library/sys.po
- [ ] howto/unicode.po

Hors top 50 des stats:
- [ ] faq.po **Réservé par @poliorcetics**
- [ ] library.po/cmath.rst **Réservé par @RobinPetit**

Pour travailler sur une section moi je m'y prend comme ça:
- Extraire la section avec msggrep
- La traduire avec Google Translate
- Travailler
- Merger
## Extraire la section avec msggrep

Pour travailler dans `library.po` typiquement, ça peut être agréable d'en extraire une partie, et msggrep rend ça facile:

```
$ msggrep -N '../Doc/library/functions.rst' 3.6/library.po > functions.po
```
## Traduire un .po avec Google Translate

L'avantage de "pré traduire" par Google Translate, c'est pour moi d'économiser des touches (je traduit sur téléphone) et parfois le vocabulaire que Google Translate trouve est intéressant et m'économise une coûteuse recherche dans ma tête.

L'astuce ici consiste à cacher les parties qu'on ne veut pas traduire à Google, du genre _:func:`str`_, car quand il traduit ça c'est chiant. Les traductions de Google sont toutes marquées, évidemment, _fuzzy_, pour ne pas les mélanger avec les vôtres, les vraies.

```
$ ./scripts/po2csv.py --untranslated-only --mangle functions.po functions.csv
$ # Upload in a Google Sheet
$ # Use googleTranslate(a1, "en", "fr") to translate them all
$ # Dowload it back as csv
$ ./scripts/csv2po.py --unmangle functions.csv functions.po
$ ./scripts/fixpo.py --only-fuzzy functions.po # To fix some typical Google Translate fuckeries
```
## Merge

Moi personnellement je traduis dans le métro, donc j'utilise Vé sur Android, dropbox pour stocker les `.po` et dropsync pour les synchroniser.

Lorsque je veux merger, j'utilise `replicate_translations.py` pour merger mes traductions dans le vrai `.po` :

```
$ ./scripts/replicate_translations.py --files 3.6/library.po functions.po
```

Je teste voir si `sphinx-doc` ne geule pas à coup de `make build RELEASE=3.6`, si sphinx gueule je ne **touche pas** à `3.6/library.po` mais à mon `.po` de travail que je re-merge via `replicate_translations.po`, comme ça mon `.po` de travail reste à jour, et je ne risque pas de me faire écraser mes fix au prochain merge.

Une fois le merge clean, je merge dans les autres versions :

```
$ ./scripts/replicate_translations.py
```

**Comment by ewdurbin** [comment]
top 50:

```
   1390 /2/tutorial/appetite.html"
   1418 /3/tutorial/datastructures.html"
   1419 /2/howto/unicode.html"
   1429 /2/library/sys.html"
   1454 /3/library/index.html"
   1519 /2/library/configparser.html"
   1528 /2/howto/regex.html"
   1638 /3/library/argparse.html"
   1653 /2/library/argparse.html"
   1806 /2/library/xml.etree.elementtree.html"
   1848 /2/library/threading.html"
   1887 /2/library/logging.html"
   1961 /3/tutorial/index.html"
   1963 /2.7/library/datetime.html"
   2085 /2/tutorial/introduction.html"
   2182 /2/library/unittest.html"
   2184 /2/library/socket.html"
   2247 /2/library/struct.html"
   2275 /2/library/sets.html"
   2285 /2/library/constants.html"
   2285 /2/library/multiprocessing.html"
   2368 /3/library/stdtypes.html"
   2376 /2/library/collections.html"
   2456 /3/search.html"
   2598 /2/library/itertools.html"
   2736 /2/library/os.path.html"
   2894 /2/library/exceptions.html"
   3026 /2/library/time.html"
   3054 /3/library/functions.html"
   3217 /2/library/subprocess.html"
   3306 /2/library/math.html"
   3764 /2/library/json.html"
   3982 /2/library/csv.html"
   3997 /2/library/random.html"
   4151 /2/tutorial/controlflow.html"
   4201 /2/library/os.html"
   4219 /2/tutorial/modules.html"
   4518 /3.4/library/builtins.html"
   4742 /2/tutorial/classes.html"
   5092 /2/search.html"
   5189 /3.5/library/builtins.html"
   6205 /2/library/datetime.html"
   6361 /2/tutorial/errors.html"
   6469 /2/library/re.html"
   6716 /2/library/string.html"
   6925 /2/library/stdtypes.html"
   7962 /2/tutorial/inputoutput.html"
   9495 /2/tutorial/datastructures.html"
  12961 /2/library/functions.html"
  26222 /2.7/library/__builtin__.html"
```

Total Line Count for sample: 2795008

**Comment by JulienPalard** [comment]
By removing a big bias introduced by a crawler crawling `/library/__builtin__.html` , we're in fact at **18.6%**, here is the current top 20%, bold are done:

 - **4.1% /library/functions.html**
 - **2.78 /tutorial/datastructures.html**
 - 2.45 /library/stdtypes.html
 - **2.35 /tutorial/inputoutput.html**
 - **1.89 /search.html**
 - **1.89 /**
 - 1.87 /library/string.html
 - 1.69 /library/re.html
 - 1.61 /library/datetime.html
 - **1.49 /tutorial/controlflow.html**
 - **1.40 /tutorial/errors.html**
 - 1.33 /library/csv.html
 - 1.27 /library/os.html
 - **1.16 /tutorial/classes.html**
 - 1.11 /library/random.html
 - 1.07 /library/json.html
 - 1.06 /library/subprocess.html
 - **1.01 /tutorial/**

**Comment by RobinPetit** [comment]
Je signale que je me lance sur `library.po` : `string.rst`.

**Comment by poliorcetics** [comment]
Je suis en train de beaucoup avancer sur la faq (je n'avais pas vu que quelqu'un l'ait déjà prise).

**Comment by JulienPalard** [comment]
@poliorcetics: Je n'ai pas de nouvelle depuis fin janvier (https://github.com/AFPy/python_doc_fr/issues/31) sur la réservation de la faq, il y a peu de chance qu'il y ai conflit, @amaddah qu'en est-il ?

**Comment by amaddah** [comment]
@JulienPalard ; yop, pas de soucis, je n'ai plus avancé sur la faq depuis fin janvier. Bon courage @poliorcetics

**Comment by RobinPetit** [comment]
J'ai fait `library.po : cmath.rst`, et je me lance sur `library.po : math.rst`.

**Comment by JulienPalard** [comment]
@RobinPetit wah nice, n'hésite pas à pull-request.

**Comment by Nodraak** [comment]
Bonjour,
Je m'occupe du module `library/datetime`

**Comment by RobinPetit** [comment]
Je me charge de `library/os`.

**Comment by grenoya** [comment]
@Nodraak : où en es tu avec datetime ? as tu besoin d'aide ?

**Comment by grenoya** [comment]
Je réserve library/re

**Comment by Nodraak** [comment]
@grenoya J'avais pas mal avancé avant l'été (je suis environ aux 3/4 de memoire), mais j'avoue que j'ai complétement oublié de finir. Tu peux trouver tout ce que j'ai fait sur [mon fork](https://github.com/Nodraak/python_doc_fr), branch `translation/datetime`. Je viens de *squash* les commits, mais le *rebase* foire, j'essayerais de regarder et de terminer la traduction dès que possible :)

**Comment by crunchylian** [comment]
Salut !
Je vais prendre le howto pour les regex. :)

**Comment by crunchylian** [comment]
Salut !
Je vais prendre le howto pour les regex. :)

**Comment by Shloub** [comment]
Bonjour,

Je vais m'essayer à library/csv.po
