### ISSUE TITLE
Discussions sur les traductions et les conventions.

### ISSUE THREAD

**Issue by RobinPetit** [AFPy/python_doc_fr#45]
J'ouvre une issue afin de discuter des possibilités de traductions de certains mots et de certaines conventions de traductions ou typographiques. Je propose qu'on laisse celle-ci ouverte au lieu d'en créer une nouvelle pour chaque interrogation.

Voici les questions en vrac :
## Typographie
- Est-ce qu'on respecte la règle typographique de l'espace (insécable normalement) devant un point-virgule ? Je ne sais personnellement pas faire d'espace (fine) insécable sans raccourci de moins de six touches sur mon clavier donc je mets habituellement des espaces simples.
- Est-ce qu'on ajoute les points-virgules en fin de listes à puces ?
## Traductions
- **To raise** devrait se traduire par _lever_ ou _soulever_ ? J'ai personnellement presque toujours lu/entendu qu'on **lève** une exception, mais je lance le débat dessus.
- **Bitwise** devrait se traduire par _bit-à-bit_, _sur les bits de [...]_, ou autre ?

Question de cohérence : faut-il traduire les références (`:ref:`, `:term:`, etc.) et mettre le bon lien entre chevrons ? (exemple : ':term:`abstract base class`' devient ':term:`classe de base abstraite <abstract base class>`')

**Comment by JulienPalard** [comment]
## Typographie

Je pense que l'on doit respecter les différentes règles typographiques, pour l'espace insécable, avec une compose key ça se fait en 3 touches "Compose-Space-Space", mais je pense qu'on devrait faire un script pour maintenir ça, afin que ceux qui ne savent pas faire (moi sur Android typiquement) puissent réparer leurs règles typographiques en un appel à un script (`fix_style.py` ?)


## Traductions
### To raise

Je traduis *raise* par "lève", moi aussi, si quelqu'un est contre je sous ouvert au débat aussi, car je ne suis pas fan de cette traduction, pour moi "lever une alerte" c'est "l'annuler", cf le Larousse: [Faire cesser quelque chose, le faire disparaître, le supprimer : Lever une interdiction. Lever un siège](http://www.larousse.fr/dictionnaires/francais/lever/46876#hMvVk514b7Oq7awR.99)

### Bitwise

bit-à-bit me convient, c'est aussi le nom de la page Wikipédia fr pour "Bitwise operation"

### Return

Je crois qu'il y a débat sur "return" que beaucoup traduisent, typiquement à l'oral "retourne". Je trouve que "retourne", bien que sémantiquement correct ("retour à l'expéditeur") est ambigu ("retourne une string" "retourne une liste"; "Il la retourne ou pas ?"). Je préfère donc, en fonction du contexte, soit "donne", soit "renvoie".

 - Donne : J'utilise *donne* dans le cas où la valeur *renvoyée* n'a aucun rapport avec la valeur soumise, comme dans "Donne ``True`` si la chaîne est en majuscule".
 - Renvoie : J'utilise *renvoie* dans le cas où la valeur *renvoyée* est la valeur soumise modifiée, comme dans "Renvoie la chaîne en majuscules".

Qu'en pensez-vous ?

**Comment by RobinPetit** [comment]
Pour la typo, je suis d'accord pour le script (parce que je n'ai pas de compose sur mon clavier.

## Raise

pour ne pas avoir la sémantique d'*annuler*, il y a l'option *lancer une exception* comme le mot-clef *throw* en C++/Java.

## Return

Pour *return*, il y a effectivement un débat, je l'ai personnellement traduit *retourne* mais *renvoie* me semble bien aussi. La convention me semble honorable.
