### ISSUE TITLE
intéressé pour participer si c'est simple 

### ISSUE THREAD

**Issue by deronnax** [AFPy/python_doc_fr#48]
Hello.
Tout d'abord, bravo pour ce que vous faites.
Ensuite, je voulais signaler que je serais partant pour participer à la traduction de la documentation si c'est simple, genre comme [transifex](https://www.transifex.com/). C'est vraiment bien fichu, y'a la string à traduire, un champs déjà traduit automatiquement à corriger, et on fait "next", "next", "next". J'ai déjà fait quelques traductions pour Django avec Transifex. J'en ai pas encore trouvé la preuve, mais je pense que comme beaucoup de produits IT de grosses compagnies moderne, c'est gratuit pour les projets open source (comme Pycharm par exemple).
Voila, si y'a un transifex ou similaire, je participerai :)

(non, je ne travaille pas pour Transifex)

**Comment by HS-157** [comment]
C'est vrai, il faudrait mettre en place un outils en ligne qui permettrait de traduire directement sans avoir à cloner le dépôt. Je pense que ça sera plus simple pour les personnes qui vondront traduire spontanément.

Mais Transiflex était un outil privatif, je ne suis pas pour l'utiliser. Il existe des outils _"Transiflex-like"_ sous licence libre qu'on peut déployer ou chercher s'il existe des instances ouvert à tous où on peut se mettre.

Si ces outils libre peuvent être inter-opérable avec Transiflex (ou Transiflex être inter-opérable avec eux), alors pourquoi pas utiliser Transiflex mais qu'il deviennent pas l'outil principal de traduction.

Traduit avec Google Traduction ↓

----------

Translated with Google Translate ↓

True, it would set up an online tool that would translate directly without having to clone the repository. I think it will be easier for people vondront translate spontaneously.

But Transiflex was a private tool, I am not to use it. There are tools _"Transiflex-like"_ free license that can deploy or look if there are open to all instances where one can get.

If these free tools can be interoperable with Transiflex (or Transiflex be interoperable with them), then why not use Transiflex but not become the primary translation tool.

**Comment by amirouche** [comment]
bof!

**Comment by grenoya** [comment]
@deronnax attention à ne pas confondre : Transifex ne traduit pas, il ne fait qu'héberger et proposer une interface web. Si dans tes précédents projets tu avais des morceaux déjà traduits et juste à corriger c'est que qqun avait déjà enregistré une traduction.
Le boulot reste le même que l'on passe par une interface web ou que l'on passe par github + éditeur spécialisé (poedit, ...) : il faut traduire une première fois les chaînes et modifier les traductions si elles ne sont pas assez bonnes ou si la phrase d'origine à changé (fuzzy translations).

En dehors de ce malentendu, je n'ai rien contre la mise en place d'un tel outil, tant que la synchronisation est maintenue avec le dépôt Github.

**Comment by JulienPalard** [comment]
J'en ai parlé avec le papa de la traduction japonaise hier, et avant que je dise "ouf" il a renommé son repo transifex de "python-doc-ja" en "python-doc".

J'ai aussi contacté les argentins mais je n'ai pas trouvé le mail du papa de la traduction russe. On va voir si tout le monde est chaud pour tout mutualiser, ce serait propre.

**Comment by deronnax** [comment]
@grenoya hmm je semble me souvenir que les string portaient une mention "pré-traduites automatiquement par google trad", mais peut être que je me trompe, mais ce point n'est pas très important.

Je voudrais insister sur un point : seul compte la meilleure solution technique, que ça soit privateur ou pas ne rentre pas vraiment en ligne de compte, du fait que notre travail ne sera pas prisonnier de Transifex. De ce point de vue-là justement, ça n'est pas "privateur": nos données nous appartiennent toujours, tout le temps. Transifex n'est qu'une interface, le jour où nous voulons changer, ils nous "suffit" de le fire. Je ferai pour ce cas un parallèle avec le cas CPython, qui après avoir beaucoup hésité entre plusieurs solutions et était réticent à utiliser Github, est finalement passé sur Github: comme le développement de CPython, la traduction est fait majoritairement par des gens non rémunérés qui font ça sur le peu de temps libre qu'ils ont. La meilleure solution est celle qui permis d'accomplir le maximum de travail en un minimum de temps, et également d’enrôler facilement de nouveaux contributeurs, sans mettre évidement le traval accompli en danger ; et c'est là que Transifex & co se posent, et ne mettent pas la propriété/liberté de notre travail en danger. Ce n'est pas comme si, par exemple, ce travail était hébergé chez Azure ou AWS.

Le fait qu'elle soit "privateur" n'est pas très important (bien que je préfère le libre, évidemment) : en l’occurrence, nos traductions ne seront pas prisonnières de Transifex ou autre, elles ne seront pas moins bonne parce que collectées par une "solution privatrice".

Pour refaire un parallèle avec mon cas : traduire m'intéresse. La compilation des docs, l’interpolation des strings, les erreurs d'autotools, toute la technique qui y est liée, ne n'intéresse pas :)

**Comment by grenoya** [comment]
Je te rassure, même avec Github + poedit (ou autre), seule la traduction 
est à la charge des traducteurs, le reste se fait après le commit ou la 
PR, par nous (surtout Mandark).

On offre la possibilité aux gens de recompiler chez eux pour voir le 
résultat s'ils n'ont pas la patience d'attendre que l'on mette à jour, 
mais c'est tout.

Pour l'aspect fédérateur on est bien d'accord, et MAndark est en 
discussion avec les responsables des autres communautés l10n de Python 
pour avoir un unique Tx.

**Comment by JulienPalard** [comment]
On parle de transfiex et de python-doc-ja, à ce propos j'ai une question pour vous : https://github.com/AFPy/python_doc_fr/issues/49

**Comment by JulienPalard** [comment]
J'essaye actuellement de synchroniser notre travail entre la branche https://github.com/AFPy/python_doc_fr/tree/split (compatible avec https://www.transifex.com/python-doc/) mais j'ai [des](https://github.com/transifex/transifex-client/issues/140) [problèmes](https://github.com/transifex/transifex-client/issues/141). Si quelqu'un maîtrise mieux transifex que moi il peut y jeter un œil, sinon j'aurai bien une réponse de transifex sur github…

**Comment by JulienPalard** [comment]
Voilà nos traductions sont synchronisées sur https://www.transifex.com/python-doc/python-35/.
