### ISSUE TITLE
Vote: Drop gettext_compact

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/python_doc_fr#49]
Hello,

I propose to drop [gettext_compact](http://www.sphinx-doc.org/en/stable/config.html#confval-gettext_compact) (in other word, explicitly set `gettext_compact=0` in `sphinx-doc -b gettext`).

python-doc-ja dropped it and it looks more readable: https://github.com/python-doc-ja/py35-locale/tree/master/ja/LC_MESSAGES/library. Also I suspect we'll have to do so if we want to share their transifex project, which they kindly renamed [python-doc](https://www.transifex.com/python-doc/) instead of `python-doc-ja`.

It'll avoid us to use `msggrep` to split `library.po`, which contains like 25k msgids and 155k lines.

I'll read your votes as +1, 0, -1. +1000 and -1000 allowed to express your opinion but will count as +1/-1.

**Comment by grenoya** [comment]
+1

**Comment by JulienPalard** [comment]
I created a branch https://github.com/AFPy/python_doc_fr/tree/split so you can inspect what the result may be.

**Comment by JulienPalard** [comment]
Merged.
