### ISSUE TITLE
Proposition d'évolution du script de génération du tableau de progression

### ISSUE THREAD

**Issue by grenoya** [AFPy/python_doc_fr#50]
J'ai ajouté le script progression.py qui génère (en Python) le tableau de progression que l'on avait dans le README avant changement de l'arborescence du dépôt.

Attention : il ne faut pas encore l'utiliser pour mettre à jour le readme car l'option "--update-readme" ne fait pas ce qu'il faut pour le moment (il va écraser le fichier au lieu de la mettre à jour...). Je veux bien de l'aide là dessus.

La prochaine évolution majeure de ce script est une liste de sous blocs de library, faq, ... que l'on voudrait faire apparaître dans le tableau en plus ( comment comptabiliser ?) des lignes générales.
Quels sous-blocs faudrait-il faire apparaître dans un premier temps ?

**Comment by JulienPalard** [comment]
J'ai fixé la partie `--update-readme`, ajouté argparse, coupé la fonction `check_progress` pour la rendre plus simple a modifier si tu veux réorganiser les sections, utilisé OrderedDict, et pour le format_progress j'ai utilisé un module `tabulate`.

Côté "liste des sous blocs de library" c'est compliqué à afficher, y'en a … beacuoup (301).

On pourrait n'afficher que ceux qui n'ont ni 0 ni 100% de progression ?
