### ISSUE TITLE
Petite erreur de traduction (3.1.3)

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [AFPy/python_doc_fr#63]
Je pense que dans
https://docs.python.org/fr/3.5/tutorial/introduction.html#lists
````
Mais à la différence des listes qui sont immuables, les listes sont mutables : il est possible de changer leur contenu :
````
il faut remplacer la première occurrence de 'listes' par 'chaînes'. 

Sur un point annexe, ne faudrait-il aussi utiliser 'muables' plutôt que 'mutables' ?

**Comment by JulienPalard** [comment]
Bonjour, merci beaucoup pour ce bug report ! 

Note que ce repo n'est plus actif, on a migré chez https://github.com/python/python-docs-fr/.

J'ai regardé et ça à été corrigé dans le commit https://github.com/python/python-docs-fr/commit/77b66e2cc016725027be964ded9c292b8c9888f2, mais la 3.5 n'est plus compilée, vu qu'elle n'accepte plus que les bug fix.

Il faudrait effectivement un moyen de la recompiler de temps en temps pour les traductions, je vais voir ce que je peux faire.

Pour "muables" vs "mutables" on retrouve "mutable" dans le dictionnaire de l'Académie Française,et le Larousse:

> (1)*MUTABLE adj. XVIe siècle. Emprunté du latin mutabilis, de même sens.  1. BIOL. Qui est sujet à mutation. Gène mutable.  2. ADM. Qui peut être muté.

Mais on ne retrouve pas "muable", ni dans le dictionnaire de l'académie Française, ni dans le Larousse, ni dans le Grand Dictionnaire Terminologique de l'office québécois de la langue française. cependant on le retrouve chez [cnrtl](http://www.cnrtl.fr/definition/muable) : "Qui peut être mué, transformé, changé.".

On a cependant bien "immuable", dans les deux dictionnaires :

> (1)IMMUABLE adj. XIVe siècle. Dérivé de muable.  1. Qui n'est pas sujet au changement. Dieu est immuable. Les lois immuables de la nature.  2. Qu'on suppose à l'abri du changement. Une décision immuable. Une volonté immuable. Vouer à quelqu'un une amitié immuable. Par ext. Ferme, résolu. Il est immuable dans ses opinions.

Mais on a pas "immutable", ni dans l'un ni dans l'autre.

Côté éthymologie on a "muable" de "muer" qui selon l'académie française peut signifier "Changer, transformer.". De l'autre côté on a "mutable" de "muter" qui selon l'académie française parle de changement de poste ou de biologie:

> 1. ADM. Affecter à un autre poste, à un autre service. Ce fonctionnaire a été muté à Lyon. Par ext. Muter un employé au sein d'une entreprise.  2. BIOL. Subir une ou plusieurs mutations. Une cellule acquiert en mutant des caractères nouveaux transmissibles aux générations cellulaires qui en descendent.

On devrait peut être donc utiliser "muable", bien qu'il n'existe pas, plus propre éthimologiquement, et symétrique avec "immuable", qui lui existe.
 
Je m'en vais donc écrire à l'académie française à ce sujet et essayer d'obtenir plus d'avis.

**Comment by Jean-Baptiste-Camps** [comment]
Ok, bien noté pour le changement de repo. J'ai juste suivi le lien fourni depuis l'onglet «Signaler un bug de la doc» (peut-être à mettre à jour) ?

Je vois en effet qu'on a bien _muable_ que dans le TLFI (et dans les dictionnaires d'ancien / moyen français, c'est peut-être mon tropisme médiéval qui s'exprime). Ça permet de garder mieux le parallèle avec immuable, à mon avis (et le sens est moins spécialisé). Côté étymologie, de toute façon, _muer_ et _muter_ dérivent tous deux de MUTARE en latin, le premier a suivi l'évolution de la langue parlée depuis l'Antiquité, le second est une formation savante, calquée sur le latin (apparemment pas attestée avant le XVe-XVIe).

**Comment by JulienPalard** [comment]
Pareil ce lien est à jour dans les versions récentes (https://docs.python.org/fr/3.6/bugs.html) mais la 3.5 n'est pas reconstruite depuis qu'on a changé ça, il faut vraiment qu'on s'y penche.

Pour immuable / muable je suis bien tenté de les autoriser, mais je vais attendre la réponse de l'académie francaise avant de tout changer.

**Comment by feth** [comment]
Bonjour,

Immuable/modifiable ?

Feth

**Comment by JulienPalard** [comment]
C'est bien aussi. pas trés symetrique mais c'est pas des maths non plus. L'avantage de la symetrie immuable/muable est qu'il est immediatement clair que les deux parlent d'une même caracteristique et sont opposés.

**Comment by JulienPalard** [comment]
Réponse de l'académie Française :

> On peut songer à changeant, instable, fluctuant.

**Comment by feth** [comment]
mardi 2017-10-24 à 16:18:25 (CEST), Julien Palard a écrit:
> Réponse de l'académie Française :
>
> > On peut songer à changeant, instable, fluctuant.
Que diriez-vous de «changeant - figé»
Parce que «instable», ça n'inspire pas confiance.

Feth

**Comment by JulienPalard** [comment]
instable n'inspire vraiment pas confiance, changeant et fluctuant ne correspond pas du tout, c'est pas "changeant" mais "changeable" ni fluctuant mais "fluctuable" qu'il nous faudrait þ

Tu as proposé modifiable, et xcombelle a proposé modifiable sur IRC aussi, j'aime bien modifiable aussi.

**Comment by JulienPalard** [comment]
"muable" a un avantage : il est clairement l'opposé de immuable, et c'est clairement binaire : soit c'est muable, soit c'est immuable.

"modifiable" a un avantage : il est plus simple à comprendre, plus accessible, et c'est notre travail aussi de rendre Python accessible.

**Comment by JulienPalard** [comment]
Nouvelle réponse de l'Académie française : 

> Dans la 6e édition muable était défini ainsi : inconstant, sujet au changement.
> Il était précisé que ce mot était peu usité.

**Comment by JulienPalard** [comment]
Ahh et le poll twitter, 50%, 50% entre muable et mutable, merci les gens. 

https://twitter.com/sizeof/status/922181164722466816

**Comment by JulienPalard** [comment]
Fixed https://github.com/python/python-docs-fr/commit/0d4bffbcf93093319e6ef4f7e569e4e993aaf76e
